### ISSUE TITLE
Relation-type filter is ignored

### ISSUE THREAD

**Issue by bencomp** [CrossRef/event-data-query#14]
When I query Event Data for `relation-type:references` or `relation-type:cites` from Zenodo (DOI prefix 10.5281, whose events are coming from DataCite), I get events with `'relation_type_id': 'is_part_of'`. I expected to only get events with the relation type that I asked for.

Example query: <http://query.eventdata.crossref.org/events?rows=100&filter=subj-id.prefix:10.5281,relation-type:references>.

**Comment by afandian** [comment]
That's a good spot. I can't immediately see the cause. (I'm afraid I'll be out of the office until the 21st.)

**Comment by afandian** [comment]
Fixed, thanks for reporting.
