### ISSUE TITLE
DOI with forward slash results in timeout

### ISSUE THREAD

**Issue by rdmpage** [CrossRef/event-data-query#5]
Calling the API with the following DOI https://doi.org/10.1093/jmammal/gyx016 results in a timeout:  https://query.eventdata.crossref.org/events?filter=work%3A10.1093%2Fjmammal%2Fgyx016

**Comment by afandian** [comment]
The syntax has changed since this was raised. Now doesn't result in a timeout (although there are no results!). https://query.eventdata.crossref.org/events?filter=obj-id:10.1093/jmammal/gyx016
